Updates a device configuration
---
tags:
  - Device
  - Configuration
parameters:
  - in: path
    name: device_id
    required: true
    type: integer
    description: Id of the device
  - in: body
    name: body
    required: true
    schema:
        type: object
responses:
  200:
    description: Success
    schema:
      type: object
      required:
        - content
      properties:
        content:
          $ref: '#/definitions/DeviceWithConfig'
