"""empty message

Revision ID: 3cf41808886b
Revises: 764de3c39771
Create Date: 2018-11-03 15:40:04.384489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf41808886b'
down_revision = '764de3c39771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_widgets', sa.Column('name', sa.String(),
        nullable=False, server_default='Legacy widget'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboard_widgets', 'name')
    # ### end Alembic commands ###
