"""empty message

Revision ID: c09252c2c547
Revises: dad1f9b4eec2
Create Date: 2018-10-30 19:33:17.778301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c09252c2c547'
down_revision = 'dad1f9b4eec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recordings', 'record_value',
               existing_type=sa.String(),
               type_=sa.Float(),
               postgresql_using='record_value::double precision')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recordings', 'record_value',
               existing_type=sa.Float(),
               type_=sa.String(),
               nullable=False)
    # ### end Alembic commands ###
